### PR TITLE
Using bootstrap project

### PR DESCRIPTION
**Pull request by nriqu322**
Built a Newsweek main page clone using bootstrap 4. 
Classes used for layout, margins, padding, color, background, positioning and alignment

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Required change 🔴

Hi @nriqu322, you are truly a gem 👐 . I can only admire your beautiful project and effort 😄 Project is very responsive. It is truly a clone indeed 👍 . However, we are getting some warnings in the [HTML markup](https://validator.w3.org/). Let us fix it and submit another code review. Great work ✋ 
Comment below:
- Let fix this
warn

Good luck with your next submission 👍 
Happy coding 💻 
Daniel Larbi Addo

**Comment by nriqu322** [comment]
Hi @addod19, They are just warnings, not errors. 
I had no problems in been approved before with those warnings, it says there to **consider** using h2 or h6, doesn't say that is mandatory.

**Comment by addod19** [comment]
Alright. Am sorry to mislead you. I should have marked it as optional.Thank you for drawing my attention to it. Submit
another code review and the next code reviewer will approve it. Nice work
👍🏽

**Comment by nriqu322** [comment]
Fixed warnings changing some divs to h2 and some display none h2 added for the sections that did not require an 'h tag' according to the original page.

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
